# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TonyDeng's Blog
subtitle: “In me the tiger sniffes the rose.” -- Siegfried Sasson
description:
author: Tony Deng
language: zh-Hans
timezone:
avatar: https://avatars1.githubusercontent.com/u/629519?v=3&s=460
since: 2014

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tonydeng.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [gitbook-zh/gitbook-howtouse/*,gitbook-zh/gitbook-howtouse/**/*]

# Writing
# new_post_name: :title.md # File name of new posts
new_post_name: :year-:month-:day-:title.md
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
# theme: landscape
theme: next

# Copy Assets
## Plugins: https://github.com/f111fei/hexo-processor-copyassets
## 能自定义source中的指定文件或文件夹，在执行generate命令的时候能直接复制到public文件夹中而不经过渲染
## 多个文件夹用,分隔
# copyAssets: gitbook-zh/gitbook-howtouse

# Index Page
index_generator:
  per_page: 10  ## 首页默认10篇文章标题

# Archive Page
archive_generator:
  per_page: 10  ## 首页默认10篇文章标题
  yearly: true  ## 生成年视图
  monthly: true ## 生成月视图
# Tag Page
tag_generator:
  per_page: 10  ## 标签分类页面默认10篇文章

# Category Page
category_generator:
  per_page: 10  ## 分类页面默认10篇文章

# Feed
feed:
  type: atom  ## feed类型，使用atom，可以使用rss2
  path: atom.xml  ## feed路径
  limit: 20 ## feed文章最小数量

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:tonydeng/tonydeng.github.io.git
  branch: master
